Поправить стилистику, орфографию и грамматику документации
spacious-team/investbook pull request #383
Opened 2021-12-06 20:00 UTC by dimio

#122

2021-12-08 11:50 UTC, vananiev requested changes
Спасибо за PR! Важные изменения. Я оставил несколько небольших комментариев.

2021-12-08 11:50 UTC, vananiev commented on docs/install-on-windows-by-zip.md
> +2. Скачать со страницы [проекта](https://github.com/vananiev/portfolio/releases/latest) скачать архив `investbook.zip`
В markdown все должно быть с `1.` Сделано синтаксически так, потому что так удобно добавлять пункты посередине списка. В рендере отображается правильная нумерация. Нужно вернуть.

2021-12-08 11:50 UTC, vananiev commented on docs/install-on-windows-by-zip.md
> +Или запустите Диспетчер задач сочетанием клавиш `Ctrl+Shift+Esc` и остановите процесс `Investbook.exe`.
Спасибо, хорошее улучшение текста. В 20ой строчке только отступ нужен.

2021-12-08 11:50 UTC, vananiev commented on docs/install-on-windows-by-zip.md
> +   из памяти компьютера. Или оставьте приложение в памяти для быстрого повторного запуска. После этого необходимо перезапустить приложение.
Не очень понял зачем после перезапустить приложение? Может имелось в виду
`Или оставьте приложение в памяти для быстрого повторного запуска, тогда для запуска приложения потребуется лишь открыть браузер` ?

2021-12-08 11:50 UTC, vananiev commented on docs/install-on-windows.md
> +   приложение `Investbook`, нажав в верхнем правом углу пиктограмму `Завершить`. Если сайт не открывается - запустите Диспетчер задач сочетанием клавиш `Ctrl+Shift+Esc`
Длинная строка, нужно перенос строки заюзать.

2021-12-08 11:50 UTC, vananiev commented on docs/install-on-windows.md
> +и остановите процесс `Investbook.exe`.
нужен отступ на 3 пробела

2021-12-08 11:50 UTC, vananiev commented on src/test/java/ru/investbook/InvestbookApplicationTest.java
> +        ;
Спасибо за тест. Давно надо их начать писать. точку с запятой в проекте обычно ставим на 66 строке, сразу после закрывающей скобки.

2021-12-09 06:27 UTC, dimio commented on docs/install-on-windows-by-zip.md
> +2. Скачать со страницы [проекта](https://github.com/vananiev/portfolio/releases/latest) скачать архив `investbook.zip`
Fix
Минус - idea автоматом перенумеровывает по порядку. Это можно как-то побороть?

2021-12-09 06:31 UTC, dimio commented on docs/install-on-windows-by-zip.md
> +Или запустите Диспетчер задач сочетанием клавиш `Ctrl+Shift+Esc` и остановите процесс `Investbook.exe`.
Fix

2021-12-09 06:31 UTC, dimio commented on docs/install-on-windows-by-zip.md
> +   из памяти компьютера. Или оставьте приложение в памяти для быстрого повторного запуска. После этого необходимо перезапустить приложение.
Ошибка копипасты. Поменял.

2021-12-09 06:35 UTC, dimio commented on docs/install-on-windows.md
> +   приложение `Investbook`, нажав в верхнем правом углу пиктограмму `Завершить`. Если сайт не открывается - запустите Диспетчер задач сочетанием клавиш `Ctrl+Shift+Esc`
Fix

2021-12-09 06:35 UTC, dimio commented on docs/install-on-windows.md
> +и остановите процесс `Investbook.exe`.
Fix

2021-12-09 06:36 UTC, dimio commented on src/test/java/ru/investbook/InvestbookApplicationTest.java
> +        ;
Fix

2021-12-09 10:06 UTC, vananiev commented on docs/install-on-windows-by-zip.md
> +2. Скачать со страницы [проекта](https://github.com/vananiev/portfolio/releases/latest) скачать архив `investbook.zip`
Может настроено как-то, я из коробки настройки пользую IDEA Ultimate 2021.3 - не перенумеровывает. Не знаю, не сталкивался.

2021-12-09 10:10 UTC, merged

2021-12-09 10:11 UTC, vananiev commented
Все в порядке, отличное начало по тестам, свежий взгляд на документацию, спасибо.