Добавил BrokerReport и BrokerReportFactory для Альфа-Инвестиций
spacious-team/investbook pull request #542
Opened 2023-05-04 19:56 UTC by embraceddd

Relates gh-71 https://github.com/spacious-team/investbook/issues/71

2023-05-06 19:47 UTC, vananiev requested changes

2023-05-06 19:47 UTC, vananiev commented on src/main/java/ru/investbook/parser/alfa/AlfaBrokerReportFactory.java
> + * Copyright (C) 2020  Vitalii Ananev <spacious-team@ya.ru>
Нужно поправить файл копирайта, вставился старый копирайт. Самый простой способ это сделать, это начать работать напрямую с этим репозиторием, но сейчас со своего репо заливаешь ветку, а твой репо устарел. Поэтому обнови develop на своем репо и сделай rebase ветки `feature-gh-71-assets` на develop. Подтянутся новые изменения, которые изменят, возможно, существующий API.

2023-05-06 19:47 UTC, vananiev commented on src/main/java/ru/investbook/parser/alfa/AlfaBrokerReportFactory.java
> +    private final Pattern expectedFileNamePattern = Pattern.compile("^[0-9]+\\([^()]+\\)[0-9\\-]+\\.xls(x)?$"); // FIXME - уточнить про регэксп
Такие комментарии лучше вставлять через `// TODO - уточнить про регэксп`. IDEA позволяет не забывать про todo при коммитах и искать все todo в пределах проекта. Что хотел уточнить?

2023-05-06 19:47 UTC, vananiev commented on src/main/java/ru/investbook/parser/alfa/AlfaBrokerReportFactory.java
> +        return brokerReport;
После обновеления ветки develop и rebase сигнатура метода обновится. Текущую версию залить и получить работоспособный код не получится. Rebase - потенциально опасен, можем сделать совместно на созвоне.

2023-05-06 19:47 UTC, vananiev commented on src/main/java/ru/investbook/parser/alfa/AlfaBrokerReportWrapper.java
> +        throw new UnsupportedOperationException();
Отлично, молодец! Такие исключения нужно вставлять, чтобы не забыть реализовать.

2023-05-06 19:47 UTC, vananiev commented on src/main/java/ru/investbook/parser/alfa/AlfaCashflowBrokerReport.java
> +            if (reportPage.findByPrefix(UNIQ_TEXT, 11, 13) == TableCellAddress.NOT_FOUND) {
В данном случае `TableCellAddress` не несет смысловой нагрузки. В таком случае нужно делать статический импорт констант, наименование `NOT_FOUND` самодостаточно - код будет читаться проще.

2023-05-06 19:47 UTC, vananiev commented on src/main/java/ru/investbook/parser/alfa/AlfaCashflowBrokerReport.java
> +        this.book.close();
`this.` используют обычно в конструкторе. В классе не используют (если есть перекрытие с локальной переменной, то можно использовать this, но лучше переименовывать локальную переменную).

2023-05-10 18:21 UTC, embraceddd commented on src/main/java/ru/investbook/parser/alfa/AlfaBrokerReportFactory.java
> +    private final Pattern expectedFileNamePattern = Pattern.compile("^[0-9]+\\([^()]+\\)[0-9\\-]+\\.xls(x)?$"); // FIXME - уточнить про регэксп
про TODO - принял

вопрос уточнил в рамках еженедельного созвона, решили соответствовать формату "Брокер 99999 (01.01.01-02.02.02)"

2023-05-10 18:23 UTC, embraceddd commented on src/main/java/ru/investbook/parser/alfa/AlfaBrokerReportFactory.java
> + * Copyright (C) 2020  Vitalii Ananev <spacious-team@ya.ru>
поправил

2023-07-31 18:32 UTC, embraceddd commented on src/main/java/ru/investbook/parser/alfa/AlfaBrokerReportFactory.java
> +        return brokerReport;
поправил

2023-07-31 18:33 UTC, embraceddd commented on src/main/java/ru/investbook/parser/alfa/AlfaCashflowBrokerReport.java
> +            if (reportPage.findByPrefix(UNIQ_TEXT, 11, 13) == TableCellAddress.NOT_FOUND) {
поправил

2023-07-31 18:33 UTC, embraceddd commented on src/main/java/ru/investbook/parser/alfa/AlfaCashflowBrokerReport.java
> +        this.book.close();
поправил

2023-10-26 17:03 UTC, vananiev commented on src/main/java/ru/investbook/parser/alfa/AlfaCashflowBrokerReport.java
> +            if (reportPage.findByPrefix(UNIQ_TEXT, 11, 13) == TableCellAddress.NOT_FOUND) {
Не залилось видимо. В PR только коммит. Сделал, стяни.

2023-10-26 17:03 UTC, vananiev commented on src/main/java/ru/investbook/parser/alfa/AlfaCashflowBrokerReport.java
> +        this.book.close();
Снова нет изменений. Поправлю сам.

2023-10-26 17:12 UTC, vananiev commented
Этот PR закрываю в пользу https://github.com/spacious-team/investbook/pull/564, который построен относительно ветки в текущем репозитории. Иначе изменения по ревью мне не удается коммитить. @embraceddd, у вас есть права коммитить вветку по https://github.com/spacious-team/investbook/pull/564 тоже.

2023-10-26 17:12 UTC, closed without merging